name: Requesting for support
description: User has need for support or has a specific question around ReaR
labels: [support/question]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for creating a support or question issue.

        Please fill in as much of the form below as you're able.
  - type: input
    attributes:
      label: support/question
      description: What is the question?
      placeholder: e.g. What is the use of `NETFS_PREFIX`?
    validations:
      required: true        
  - type: dropdown
    attributes:
      label: Platform
      description: The platform used by ReaR
      multiple: true
      options:
        - Linux ARM64
        - Linux ARMv7
        - Linux PPC64LE
        - Linux s390x
        - Linux x64
        - Other
  - type: textarea
    attributes:
      label: Output
      description: >
        A pasted output from your ReaR command that you have
        question about.
      render: output
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If any investigation has been done, please include any information
        found, such as how consistently the test fails, whether the failure
        could be reproduced locally, when the test started failing, or anything
        else you think is relevant.
